//Defines Items Slots with place holder sprites.
using System;
using UnityEngine;
using UnityEngine.UI;
//This namespace is used to detect inputs from a script.
using UnityEngine.EventSystems;

public class ItemSlot : MonoBehaviour, IPointerClickHandler
{
    [SerializeField] Image Image;

    //Finds out which panel the item being clicked is in before the player can move it.
    public event Action<Item> OnRightClickEvent;

    private Item _item;
    public Item Item  
    {
        get { return _item; }
        set {
            _item = value;

            if (_item == null)
            {
                Image.enabled = false;
            }
            else
            {
                Image.sprite = _item.Icon;
                Image.enabled = true;
            }
        }
    }

    //This is automatic code generated by line 7's IPointerClickHandler implementation.
    public void OnPointerClick(PointerEventData eventData)
    {
        //Checking for right mouse click.
        if (eventData != null && eventData.button == PointerEventData.InputButton.Right)
        {
            if (Item != null && OnRightClickEvent != null)
                OnRightClickEvent(Item);    
        }
    }

    //Might need to change "private" to "protected override", then "virtual override" in the ItemSlot script.
    //https://youtu.be/4JewzU_phTM?t=190
    protected virtual void OnValidate()
    {
        if (Image == null)
            Image = GetComponent<Image>();
    }
}
